// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqv6Co9kCj9dEsdZcPAP2CGV17rcH6cyE',
    appId: '1:359295127098:web:df791db0cba65fcd8a2f03',
    messagingSenderId: '359295127098',
    projectId: 'velocitech-auto-go',
    authDomain: 'velocitech-auto-go.firebaseapp.com',
    storageBucket: 'velocitech-auto-go.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9KM4yzaxzGWnzwJhiQWjta7Z7oORdlcg',
    appId: '1:359295127098:android:c12582adcf6f001c8a2f03',
    messagingSenderId: '359295127098',
    projectId: 'velocitech-auto-go',
    storageBucket: 'velocitech-auto-go.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu5zmIP82grGRGxcp_PbHBlykGMR_uVgk',
    appId: '1:359295127098:ios:af0e5acd80f864138a2f03',
    messagingSenderId: '359295127098',
    projectId: 'velocitech-auto-go',
    storageBucket: 'velocitech-auto-go.firebasestorage.app',
    iosBundleId: 'com.velocitech.goCustomer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCu5zmIP82grGRGxcp_PbHBlykGMR_uVgk',
    appId: '1:359295127098:ios:af0e5acd80f864138a2f03',
    messagingSenderId: '359295127098',
    projectId: 'velocitech-auto-go',
    storageBucket: 'velocitech-auto-go.firebasestorage.app',
    iosBundleId: 'com.velocitech.goCustomer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqv6Co9kCj9dEsdZcPAP2CGV17rcH6cyE',
    appId: '1:359295127098:web:237d8d41c4ae24e68a2f03',
    messagingSenderId: '359295127098',
    projectId: 'velocitech-auto-go',
    authDomain: 'velocitech-auto-go.firebaseapp.com',
    storageBucket: 'velocitech-auto-go.firebasestorage.app',
  );
}
